[package]
name = "cetkaik_traits"
license = "MIT"
description = "traits for cetkaik"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cetkaik_fundamental = "1.0.0"
